# Buildpack API version
api = "0.8"

# Buildpack ID and metadata
[buildpack]
id = "vmware-test/chmod"
version = "0.0.1"
name = "Chmod Buildpack"

# Stacks that the buildpack will work with: any
[[stacks]]
id = "*"